export const ROLES = {
  USER: 'USER',
  JOURNALIST: 'JOURNALIST',
  EDITOR: 'EDITOR',
  ADMIN: 'ADMIN',
};

export const ARTICLE_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PUBLISHED: 'PUBLISHED',
};

export const COMMENT_STATUS = {
  APPROVED: 'APPROVED',
  PENDING: 'PENDING',
  FLAGGED: 'FLAGGED',
  REJECTED: 'REJECTED',
};

export const REPORT_STATUS = {
  PENDING: 'PENDING',
  REVIEWED: 'REVIEWED',
  DISMISSED: 'DISMISSED',
};

export const REACTION_TYPES = {
  LIKE: 'LIKE',
  LOVE: 'LOVE',
  INSIGHTFUL: 'INSIGHTFUL',
  THINKING: 'THINKING',
};

export const NOTIFICATION_TYPES = {
  BREAKING_NEWS: 'BREAKING_NEWS',
  COMMENT_REPLY: 'COMMENT_REPLY',
  EDITORIAL_STATUS: 'EDITORIAL_STATUS',
  SYSTEM: 'SYSTEM',
};

export const STORAGE_PROVIDERS = {
  LOCAL: 'LOCAL',
  S3: 'S3',
  CLOUDINARY: 'CLOUDINARY',
};
